### ISSUE TITLE
Module import doesn't seem to obfuscate

### ISSUE THREAD

**Issue by michnay** [SoftHeroes/JSObfuscator#2]
Hey Guys, please find code below. It obfuscates fine unless I comment out the module import statement. That line doesn't seem to obfuscate. Thanks for letting me know what the issue is.
Many thanks and great work, love the tool!

```javascript
export default class Test {
    myMethod() {
        (async () => {
            //The below line fails to obfuscate. If you comment it out, the file obfuscates fine.
            const myModule = await import('some path to a JS module');
        })();   
    }
}
```

**Comment by SoftHeroes** [comment]
Hey @michnay,

Published an update with fixes.
Check if working fine now. If still not feel free to reopen the issue or create a new issue.
