### ISSUE TITLE
Does not function in VSCode Version: 1.49.2

### ISSUE THREAD

**Issue by needz** [SoftHeroes/JSObfuscator#3]
It just doesn't create any new file, unfortunately. I tried everything possible.

Thanks!

**Comment by SoftHeroes** [comment]
Hey @needz,

Can you share log and video/Gif of issue?

**Comment by needz** [comment]
Hi,

Sure, here it is. You can see there are no files created after I apply the extension to Javascript file.

Thanks

**Comment by huilang-me** [comment]
> It just doesn't create any new file, unfortunately. I tried everything possible.
> 
> Thanks!

Me too. Just nothing happen.

**Comment by JayC-SF** [comment]
Hello, I tried to Obfuscate my javascript file and it doesn't seem to work. 
VsCode version: 
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-54-generic

![Peek 2020-11-25 18-36](https://user-images.githubusercontent.com/61133675/100292063-782af300-2f4d-11eb-9668-1b792b5663f8.gif)

I have tried all the instructions from the extensions page, and still nothing. Is there any way to fix it? 

Thank you very much!
jcsf

**Comment by SoftHeroes** [comment]
Hey @JayC-SF,

I know these extensions have some issues based on the code in the file. But, When I do test with my demo code it works on that file.

If your file content **_import_** syntax. The [issue](https://github.com/SoftHeroes/JSObfuscator/issues/2) is already entered.I try to fix this ASAP currently gonig very busy.

if your code file doesn't have import syntax. Can you send me some demo code so I can able to reproduce the issue and apply the fix?

Thanks,
Shubham

**Comment by SoftHeroes** [comment]
Hey @JayC-SF, @needz, @huilang-me 

Published an update with fixes.
Check if working fine now. If still not feel free to reopen the issue or create a new issue.

**Comment by huilang-me** [comment]
![image](https://user-images.githubusercontent.com/7547987/100560869-1de5b580-32f2-11eb-96e1-b32fb056e856.png)

Thanks for the update.

I have updated to v1.3.2, but it still not work.
