### ISSUE TITLE
No obfuscated file is created in Code 1.51.1

### ISSUE THREAD

**Issue by needz** [SoftHeroes/JSObfuscator#4]
The issue still persists, no file is created when obfuscating a JS file is v1.3.2

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Comment by SoftHeroes** [comment]
Hey @needz,
Can you share Log and extension settings with me

Thanks,

**Comment by needz** [comment]
I would gladly do, but please share the steps to make it. Thanks

**Comment by SoftHeroes** [comment]
Before following updated extension and reload vscode

Steps,

1. Open workspace (which contains *.js file)
2. Open one js file 
3. Press Ctrl + Shift + P
4. Search JSObfuscated  and run file command
5. If error come follow below steps

For error ----
6. Open Terminal goto output 
7. Select JSObfuscated from drop down 
8. Copy log and share with me 

It will be nice if you can able to share js file ( if possible)

Thanks

**Comment by needz** [comment]
@SoftHeroes, unfortunately, nothing happens, when I do the steps, and there are no errors shown in the Terminal output.

I am pasting the file contents here:

`var numKeyArray = new Array(17, 101, 98, 6, 8, 9, 10, 12, 13, 14);

var VK_1 = 101;
var VK_2 = 98;
var VK_3 = 6;
var VK_4 = 8;
var VK_5 = 9;
var VK_6 = 10;
var VK_7 = 12;
var VK_8 = 13;
var VK_9 = 14;
var VK_0 = 17;

var VK_PREV_CH					= 259;

var VK_ENTER					= 29443;
var VK_PAUSE					= 74;
var VK_PAGE_UP					= 68;
var VK_PAGE_DOWN				= 65;
var VK_LEFT						= 4;
var VK_UP						= 29460;
var VK_RIGHT					= 5;
var VK_DOWN						= 29461;

var VK_VOL_UP 					= 7;
var VK_VOL_DOWN 				= 11;
var VK_MUTE 					= 27;

var VK_CHLIST					= 84;
var VK_GUIDE					= 651;
var VK_TOOLS					= 75;

var VK_ASPECT 					= 653;
var VK_SUB						= 652;
var VK_SEARCH					= 1252;

var VK_RED						= 108;
var VK_GREEN					= 20;
var VK_YELLOW					= 21;
var VK_BLUE						= 22;
var VK_REWIND					= 69;
var VK_STOP						= 70;
var VK_PLAY						= 71;
var VK_FAST_FWD					= 72;
var VK_INFO						= 31;

var VK_SKIP_FWD					= 1078;
var VK_SKIP_BACK				= 1080;

var VK_BACK						= 88;
var VK_BACK_SPACE;
var VK_EXIT						= 45;
var VK_I						= 73;
var VK_E						= 69;
var VK_B						= 66;
var VK_L						= 76;
var VK_Y						= 89;
var VK_R						= 82;

var VK_3D						= 1219;
var VK_TTX_MIX					= 650;
var VK_REC						= 192;

var VK_WLINK					= 115; // SmartHub:
var VK_SEARCH 					= 1252;	//Search:
var VK_SOCIAL 					= 1251;	// Social TV	
var VK_CONTENT 					= 261;
`

**Comment by SoftHeroes** [comment]
![testDemo](https://user-images.githubusercontent.com/24780408/100733985-ff1c1780-33f4-11eb-96cd-d165dafe70f6.gif)

It's working for me can you record the screen and share here.

use this software https://www.cockos.com/licecap/

Thanks,
Shubham

**Comment by needz** [comment]
Could not use your software (blank screen only), attaching MOV capture.

**Comment by SoftHeroes** [comment]
@needz 

where is MOV?

**Comment by needz** [comment]
http://mvv.lt/github/obfuscate.mov

**Comment by SoftHeroes** [comment]
Hey @needz,

I understand why it's not working. Your file name is a problem.

Solutions: 

1st solution:  Change filename to something else.

2nd solution: Change File Extension name in settings


I am closing this issue now. You can enter one dedicated issue if you feel.

**Comment by needz** [comment]
How is my filename a problem exactly?!

**Comment by SoftHeroes** [comment]
Ohh It very clear in read me

Check the below link for detail about how this extension work.

This extension has much more features.you fully customizable how JS obfuscate.


This why your file skip:

https://github.com/SoftHeroes/JSObfuscator#overwrite-existing-files

https://github.com/SoftHeroes/JSObfuscator#settings

**Comment by needz** [comment]
Actually no, there is nothing in the settings that would NOT write the file, because I have all the default options.

It doesn’t add .obfuscated.js, and the file name is obfuscate.js , not obfuscated.js.

I tried to change it to min.js in app’s settings, but it doesn’t solve anything.
